# Generated by Django 2.2 on 2021-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
