# Generated by Django 2.2 on 2021-09-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210912_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
